# -*- coding: utf-8 -*-
"""m1_cvrp_dfj_lazy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/genoadev/treinamentos/blob/main/otimizacao_aplicada/notebooks/m1_cvrp_dfj_lazy.ipynb

# M1 — CVRP com DFJ + lazy constraints (Gurobi)

**Treinamento de Otimização Aplicada — Genoa para Gradus**

Este notebook implementa **apenas** a 3ª abordagem do CVRP — `DFJ + lazy constraints` no Gurobi — para a turma ver isolado:

1. **Modelo base** sem restrições de subtour (cobertura + capacidade + fluxo)
2. **Detector de ciclos** num grafo dirigido (helper simples)
3. **Callback** que detecta subtour e adiciona DFJ on-the-fly
4. **`Params.LazyConstraints = 1`** + `m.optimize(callback)` para fechar o loop

Os 4 pontos-chave da API de callbacks do Gurobi estão marcados como `① ② ③ ④` no código.

**Instância:** mesma Beerlink Distribuição (CD em Pinheiros + 8 bares em SP). Demanda total 340 cx/sem, capacidade do caminhão 100 cx.

> **Por que DFJ+lazy é o padrão industrial?** MTZ tem $O(n^2)$ restrições upfront — degrada exponencialmente. DFJ tem $O(2^n)$ restrições no pior caso, mas você adiciona **só as que aparecem violadas**. Em problemas reais (50–100+ clientes), separação on-demand é o que viabiliza CVRP exato. Solvers open-source (CBC, GLPK) não oferecem callbacks robustos.
"""

"""## Setup
"""

!pip install -q gurobipy matplotlib

import math, time
from itertools import product, combinations
import gurobipy as gp
from gurobipy import GRB
import matplotlib.pyplot as plt

# Versão limited-size (free) cobre o caso Beerlink (< 2.000 variáveis)
# Para problemas maiores: licença Academic, WLS ou Commercial — conversem com a Genoa.
print(f'Gurobi {gp.gurobi.version()}')

"""## Dados — Beerlink Distribuição
"""

# Coordenadas aproximadas (lat, lon) — CD + 8 bares em SP
COORDS = {
    'CD':            (-23.567, -46.685),
    'Centro':        (-23.553, -46.635),
    'Pinheiros':     (-23.565, -46.685),
    'Vila Madalena': (-23.555, -46.692),
    'Moema':         (-23.605, -46.665),
    'Tatuapé':       (-23.539, -46.572),
    'Lapa':          (-23.521, -46.706),
    'Itaim':         (-23.583, -46.671),
    'Brooklin':      (-23.612, -46.690),
}
NODES = list(COORDS.keys())
N = range(len(NODES))         # 0 = CD, 1..8 = bares
B = range(1, len(NODES))      # só bares
V = range(4)                  # até 4 veículos

# Demanda por bar (caixas/semana). CD = 0.
d = [0, 55, 30, 50, 45, 60, 35, 40, 25]

# Capacidade do caminhão
Q = 100

# Matriz de distâncias (km) — Euclidiana aproximada
def km(a, b):
    return math.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2) * 111

dist = [[km(COORDS[NODES[i]], COORDS[NODES[j]]) for j in N] for i in N]

print(f'{len(NODES)} nós ({len(B)} bares + CD), {len(V)} veículos, demanda total {sum(d)} cx/sem, Q={Q}')

"""## 1) Modelo base — *sem* restrições de subtour

Variáveis: `x[i,j,v]` binária (arco $(i,j)$ no veículo $v$), `y[i,v]` binária (bar $i$ atendido por veículo $v$).
Restrições: cobertura, capacidade, fluxo. **NADA de MTZ, NADA de DFJ upfront.**
"""

def build_base_cvrp_model(N, V, B, d, dist, Q):
    '''Monta modelo CVRP "limpo": cobertura + capacidade + fluxo. Sem subtour.'''
    m = gp.Model('cvrp_dfj_lazy')
    m.Params.OutputFlag = 0

    # Variáveis (tupledicts)
    x = m.addVars(N, N, V, vtype=GRB.BINARY, name='x')
    y = m.addVars(B, V,    vtype=GRB.BINARY, name='y')

    # (1) cada bar atendido por exatamente 1 veículo
    m.addConstrs((y.sum(i, '*') == 1 for i in B), name='cob')

    # (2) capacidade por veículo
    m.addConstrs((gp.quicksum(d[i]*y[i,v] for i in B) <= Q for v in V), name='cap')

    # (3) fluxo: entra == y == sai (por veículo)
    m.addConstrs((x.sum('*', j, v) == y[j,v] for j in B for v in V), name='in')
    m.addConstrs((x.sum(i, '*', v) == y[i,v] for i in B for v in V), name='out')

    # (3b) veículo sai do depot no máximo uma vez
    m.addConstrs((x.sum(0, '*', v) <= 1 for v in V), name='dep_out')
    m.addConstrs((x.sum('*', 0, v) <= 1 for v in V), name='dep_in')

    # (3c) sem auto-arcos
    m.addConstrs((x[i,i,v] == 0 for i in N for v in V), name='no_self')

    # FO: minimizar distância total
    m.setObjective(
        gp.quicksum(dist[i][j]*x[i,j,v] for i,j,v in product(N,N,V) if i != j),
        GRB.MINIMIZE)

    return m, x, y

m, x, y = build_base_cvrp_model(N, V, B, d, dist, Q)
print(f'Modelo construído: {m.NumVars} variáveis, {m.NumConstrs} restrições')

"""## 2) Helper: detector de ciclos

Dado o conjunto de arcos selecionados na solução incumbente, retorna a lista de **ciclos** (componentes conexas que formam loops). DFS clássico — uns 10 linhas.
"""

def find_cycles(arcs):
    '''Encontra todos os ciclos no grafo dirigido formado por `arcs`.
    Retorna lista de listas de nós (cada ciclo).'''
    succ = {i: j for i, j in arcs}           # i → j (1 sucessor por nó no CVRP)
    visited = set()
    cycles = []
    for start in succ:
        if start in visited:
            continue
        cycle, node = [], start
        while node not in visited and node in succ:
            visited.add(node)
            cycle.append(node)
            node = succ[node]
        # Se voltamos ao início, é ciclo válido
        if node == start and len(cycle) > 1:
            cycles.append(cycle)
    return cycles

# Sanity check
print(find_cycles([(1,2),(2,3),(3,1),(4,5),(5,4)]))   # [[1,2,3],[4,5]]

"""## 3) O callback — coração da abordagem

Quatro pontos-chave anotados como `① ② ③ ④`:
1. Filtra por `where == GRB.Callback.MIPSOL` — só dispara em soluções inteiras candidatas
2. Usa `cbGetSolution` (NÃO `.X` — modelo travado durante callback)
3. Adiciona constraint via `cbLazy` (NÃO `addConstr`)
4. **Obrigatório:** `Params.LazyConstraints = 1` antes do `optimize`
"""

n_lazy_added = 0   # contador para diagnóstico

def subtour_callback(model, where):
    global n_lazy_added
    if where != GRB.Callback.MIPSOL:                    # ① só em soluções inteiras
        return
    sol = model.cbGetSolution(model._x)                 # ② lê solução incumbente
    for v in V:
        arcs = [(i,j) for i,j in product(N, N)
                if i != j and sol[i,j,v] > 0.5]
        for S in find_cycles(arcs):                     # detecta ciclos
            if 0 in S:                                  # rota legítima (passa pelo CD)
                continue
            # ③ achou subtour S → adiciona DFJ on-the-fly
            model.cbLazy(
                gp.quicksum(model._x[i,j,v]
                            for i,j in combinations(S, 2)) <= len(S) - 1)
            n_lazy_added += 1

print('Callback definido — pronto para acoplar ao modelo.')

"""## 4) Resolver com `LazyConstraints = 1`
"""

m._x = x                            # handle p/ callback acessar
m.Params.LazyConstraints = 1        # ④ ⭐ ativa lazy (obrigatório)
m.Params.OutputFlag = 1             # log do solver

t0 = time.perf_counter()
m.optimize(subtour_callback)        # ⭐ passa callback ao solver
elapsed = time.perf_counter() - t0

print(f'\n→ Custo total: {m.ObjVal:.2f} km')
print(f'→ Lazy constraints adicionadas: {n_lazy_added}')
print(f'→ Tempo: {elapsed*1000:.0f} ms')

"""## 5) Extrair e mostrar as rotas
"""

def extract_routes(x, V, N):
    '''Reconstrói a sequência de visita de cada veículo.'''
    routes = []
    for v in V:
        # Arcos selecionados pelo veículo v
        arcs = [(i,j) for i,j in product(N, N) if i != j and x[i,j,v].X > 0.5]
        if not arcs:
            continue
        succ = {i: j for i, j in arcs}
        route, node = [0], 0
        while node in succ and succ[node] != 0:
            node = succ[node]
            route.append(node)
        route.append(0)   # fecha no CD
        routes.append(route)
    return routes

routes = extract_routes(x, V, N)
for k, r in enumerate(routes, 1):
    nomes = ' → '.join(NODES[i] for i in r)
    carga = sum(d[i] for i in r if i != 0)
    dist_r = sum(dist[r[t]][r[t+1]] for t in range(len(r)-1))
    print(f'V{k}: {nomes}  |  carga={carga} cx · dist={dist_r:.1f} km')

"""## 6) Visualização das rotas
"""

fig, ax = plt.subplots(figsize=(9, 7))
cores = ['#2e7d32', '#1f4e79', '#c0392b', '#a05a00']

# Plota pontos
for i, n in enumerate(NODES):
    lat, lon = COORDS[n]
    cor = '#f29200' if i == 0 else '#1f4e79'
    sz  = 280 if i == 0 else 120
    ax.scatter(lon, lat, s=sz, c=cor, zorder=3, edgecolors='white', linewidth=2)
    ax.annotate(n, (lon, lat), xytext=(5, 5), textcoords='offset points', fontsize=10)

# Plota rotas
for k, r in enumerate(routes):
    cor = cores[k % len(cores)]
    for t in range(len(r) - 1):
        i, j = r[t], r[t+1]
        lat_i, lon_i = COORDS[NODES[i]]
        lat_j, lon_j = COORDS[NODES[j]]
        ax.annotate('', xy=(lon_j, lat_j), xytext=(lon_i, lat_i),
                    arrowprops=dict(arrowstyle='->', color=cor, lw=2))
    ax.plot([], [], '-', color=cor, lw=2.5, label=f'V{k+1}')

ax.set_xlabel('Longitude'); ax.set_ylabel('Latitude')
ax.set_title(f'CVRP DFJ+lazy — Beerlink ({m.ObjVal:.1f} km, {n_lazy_added} lazy cuts)')
ax.legend(loc='lower left'); ax.grid(alpha=0.3)
plt.tight_layout(); plt.show()

"""## Lições deste notebook

- O **modelo base** tem só $O(n \cdot |V|)$ restrições — muito menor que MTZ.
- O **callback** roda algumas vezes durante o B&B; cada chamada adiciona ~1 restrição DFJ.
- O `LazyConstraints = 1` é o que **ativa** o mecanismo — esquecer essa flag é o erro #1 de quem está começando.
- `cbGetSolution` ≠ `.X` (durante o solve, use o `cb*`).
- `cbLazy` ≠ `addConstr` (durante o solve, use o `cb*`).

**Quando isso vale a licença Gurobi:** para a Beerlink com 8 bares, MTZ resolve em 500 ms — não precisa. Em rede real (40+ pontos), MTZ degrada e DFJ+lazy é o que viabiliza solver exato. Conversem com a Genoa sobre licenciamento Gurobi quando seu problema chegar nessa escala.
"""
