# -*- coding: utf-8 -*-
"""m1_frota_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/genoadev/treinamentos/blob/main/otimizacao_aplicada/notebooks/m1_frota_template.ipynb

# M1 — Dimensionamento de Frota

**Treinamento de Otimização Aplicada — Genoa para Gradus**

## Caso: Beerlink Distribuição

Maurício, da Cervejaria Beerlink (treinamento 1), passou um ano. A Beerlink cresceu — hoje abastece **8 bares** em São Paulo a partir do CD em Pinheiros.

Hoje paga frete avulso. Quer estruturar entrega própria, **alugando** caminhões refrigerados:

- Capacidade: **100 caixas / viagem**
- Aluguel: **R$ 2.000 / semana** por caminhão (com motorista)
- Combustível: **R$ 4 / km**
- Cada caminhão faz **1 viagem por semana** (segundas)

**Pergunta:** quantos caminhões alugar e quais bares cada um atende?

Para esse módulo simplificamos cada "rota" como uma **rota-estrela** (ida-volta direta ao bar mais distante do cluster). VRP completo fica fora do escopo.
"""

"""> ⚠️ **Versão TEMPLATE** — algumas células contêm `# TODO` para você preencher. Se ficar travado, abra a versão solução: `m1_frota_solution.ipynb` (ou o `.py` em `scripts/`). Se estiver no Colab, o link da solução está no deck.
"""

"""## Setup — dois solvers lado a lado

A partir deste treinamento mostramos cada modelo nos **dois solvers**:

- **OR-Tools** (Google, open-source) — backbone padrão dos treinamentos Genoa
- **Gurobi** (Gurobi Optimization, comercial) — solver state-of-the-art em MIP, representado no Brasil pela **Genoa**

**Licenciamento Gurobi:**

| Modalidade | Limite | Quando usar |
|---|---|---|
| Free limited size (sem licença) | ≤ 2.000 vars, ≤ 2.000 constraints | Aprendizado, didática (todos os casos deste treinamento cabem) |
| Academic License (gratuita) | Ilimitado | Pós-graduação |
| WLS (Web License Service) | Ilimitado, multi-usuário | Implantação corporativa |
| Commercial | Ilimitado | Produção |

Os modelos aqui rodam todos no modo **free limited-size** (não precisa de licença), mas qualquer Gradus que já tenha licença Gurobi pode aplicar direto em escala.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q ortools gurobipy

from ortools.linear_solver import pywraplp
import pandas as pd

# Dados: bares, demanda semanal (caixas) e distância ao CD Pinheiros (km)
bares = pd.DataFrame({
    'bar':    ['Centro', 'Pinheiros', 'Vila Madalena', 'Moema', 'Tatuapé', 'Lapa', 'Itaim', 'Brooklin'],
    'd':      [55, 30, 50, 45, 60, 35, 40, 25],   # caixas/sem
    'dist':   [6.0, 0.5, 1.5, 4.2, 13.5, 5.8, 2.2, 5.0],  # km até o CD
})

Q = 100         # capacidade do caminhão (caixas)
RENT = 2000     # R$/sem por caminhão alugado
CKM = 4         # R$/km
MAX_TRUCKS = 6  # limite superior para evitar variáveis demais

print(bares)
print(f"\nDemanda total: {bares['d'].sum()} caixas/semana")
print(f"Mínimo teórico de caminhões: {-(-bares['d'].sum() // Q)} (lower bound = ceil(total/Q))")

"""## Modelo MILP — fleet sizing com rota-estrela

Variáveis:
- $y_j \in \{0,1\}$: caminhão $j$ alugado?
- $x_{ij} \in \{0,1\}$: bar $i$ atendido pelo caminhão $j$?
- $L_j \ge 0$: maior distância do caminhão $j$ (linearização do `max`)

Função objetivo:
$$\min\ 2000 \sum_j y_j + 8 \sum_j L_j$$

(O fator 8 = 2 · 4 vem de ida-volta × R\$/km.)

Restrições:
- cobertura: cada bar é atendido por **exatamente um** caminhão
- capacidade: a carga de cada caminhão $\le Q \cdot y_j$
- distância: $L_j \ge \text{dist}_i \cdot x_{ij}$ para todo $i, j$
"""

def solve_fleet_homogeneo(bares, Q, RENT, CKM, max_trucks):
    """Resolva o fleet sizing com rota-estrela usando OR-Tools (pywraplp, CBC).
    Retorna dict com: status, custo_total, n_caminhoes_usados, alocacao."""

    s = pywraplp.Solver.CreateSolver('CBC')
    I = range(len(bares))                       # bares
    J = range(max_trucks)                       # caminhoes

    # =================================================
    # TODO: defina as variaveis do modelo
    # =================================================
    # y[j] in {0,1}: caminhao j operacao (binaria)
    # x[i,j] in {0,1}: bar i atendido por caminhao j (binaria)
    # L[j] >= 0: distancia maxima do caminhao j (continua, para linearizar max)

    y = ...   # use s.IntVar(0, 1, ...) ou s.BoolVar(...)
    x = ...
    L = ...

    # =================================================
    # TODO: restricoes
    # =================================================
    # (1) cada bar atendido por exatamente 1 caminhao: sum_j x[i,j] == 1 forall i
    # (2) capacidade (so se y_j = 1): sum_i d[i]*x[i,j] <= Q*y[j] forall j
    # (3) distancia maxima: L[j] >= dist[i] * x[i,j] forall i,j

    # ...

    # =================================================
    # TODO: funcao objetivo + solve
    # =================================================
    # FO: minimizar RENT*sum(y) + 8*sum(L)
    # (RENT = aluguel semanal por caminhao; CKM = R$/km; ida-volta 2*L, 8 = 2*CKM*1=8 com CKM=4)

    # s.Minimize(...)
    # status = s.Solve()

    raise NotImplementedError("Complete o modelo OR-Tools acima")

"""### O mesmo modelo em Gurobi (gurobipy)

Sintaxe `gurobipy` é mais "pythonic" que OR-Tools:

- `model.addVars(...)` cria dicionário ou matriz de variáveis em uma chamada
- `quicksum` (versão otimizada do `sum`) acelera a montagem
- Indexação multi-dimensional natural com `tupledict`

O mesmo modelo MILP do caso homogêneo:
"""

import gurobipy as gp
from gurobipy import GRB

def solve_fleet_homogeneo_gurobi(bares, Q, RENT, CKM, max_trucks):
    """Mesmo modelo do solve_fleet_homogeneo, mas em Gurobi.
    Reutilize a logica acima e adapte para gurobipy:
      - m.addVars(...) cria tupledict (use indices como argumentos posicionais)
      - m.addConstrs((expr for ... in ...), name='...') com generator
      - x.sum(i, '*') eh idiomatico para soma por linha do tupledict
    """
    m = gp.Model('frota')
    m.Params.OutputFlag = 0

    # TODO: variaveis (use m.addVars)
    # y = m.addVars(range(max_trucks), vtype=GRB.BINARY, name='y')
    # x = ...
    # L = ...

    # TODO: restricoes (use m.addConstrs com generator)
    # cobertura, capacidade, linearizacao do max

    # TODO: FO e solve
    # m.setObjective(RENT*y.sum() + 8*L.sum(), GRB.MINIMIZE)
    # m.optimize()

    raise NotImplementedError("Complete o modelo Gurobi acima")

"""### Discussão

Compare a solução do modelo com o que a turma chutaria "a olho":

- **Tatuapé vai sozinho?** É o mais distante (13.5 km) e tem demanda alta (60 cx). Quase qualquer combinação com outro bar excede 100 caixas, e mesmo que coubesse, a rota até Tatuapé é cara — não compensa "economizar caminhão".
- **Pinheiros + Vila Madalena estão no centro do CD** — fáceis de juntar (80 cx, distância máx 1.5 km).
- **O algoritmo otimiza dois eixos simultaneamente:** clustering geográfico (reduz km) e capacidade (reduz #caminhões). Esses dois critérios às vezes conflitam — é aí que o solver brilha.
"""

"""---

## Exercício de extensão: frota heterogênea + múltiplas viagens

Agora a Beerlink pode escolher entre **3 tipos de caminhão** e cada veículo pode fazer **até 2 viagens / semana**:

| Tipo | Capacidade (cx) | Aluguel (R$/sem) | R$/km |
|---|---:|---:|---:|
| Pequeno | 60 | 1.500 | 3 |
| Médio | 100 | 2.000 | 4 |
| Grande | 180 | 2.800 | 5 |

### Generalização do modelo

- $y_{jt} \in \{0,1\}$: caminhão $j$ do tipo $t$ alugado?
- $x_{ijtk} \in \{0,1\}$: bar $i$ atendido pelo caminhão $j$ do tipo $t$ na viagem $k \in \{1, 2\}$
- $L_{jtk} \ge 0$: maior distância da viagem $k$ do caminhão $(j,t)$

**Cobertura:** cada bar em exatamente uma combinação $(j, t, k)$.
**Capacidade:** carga da viagem $k$ ≤ $Q_t \cdot y_{jt}$.
**FO:** soma dos aluguéis + soma dos km × R\$/km por tipo.

Implemente abaixo e compare com o resultado homogêneo:
"""

TIPOS = {
    'P': {'Q': 60,  'rent': 1500, 'ckm': 3},
    'M': {'Q': 100, 'rent': 2000, 'ckm': 4},
    'G': {'Q': 180, 'rent': 2800, 'ckm': 5},
}
MAX_PER_TYPE = 4  # até 4 caminhões de cada tipo disponíveis
VIAGENS = [1, 2]   # cada caminhão pode fazer 1 ou 2 viagens

def solve_fleet_heterogeneo(bares, tipos, max_per_type, viagens):
    solver = pywraplp.Solver.CreateSolver('CBC')
    n = len(bares)
    I = range(n)
    d = bares['d'].tolist()
    dist = bares['dist'].tolist()

    # Index sets
    J = range(max_per_type)
    T = list(tipos.keys())
    K = viagens

    # y[j,t]: caminhão j do tipo t alugado?
    y = {(j, t): solver.IntVar(0, 1, f'y[{j},{t}]') for j in J for t in T}
    # x[i,j,t,k]: bar i atendido na viagem k do caminhão (j,t)?
    x = {(i, j, t, k): solver.IntVar(0, 1, f'x[{i},{j},{t},{k}]')
         for i in I for j in J for t in T for k in K}
    # L[j,t,k]: maior distância da viagem k do caminhão (j,t)
    L = {(j, t, k): solver.NumVar(0, solver.infinity(), f'L[{j},{t},{k}]')
         for j in J for t in T for k in K}

    # Cobertura: cada bar em exatamente 1 (j,t,k)
    for i in I:
        solver.Add(sum(x[i, j, t, k] for j in J for t in T for k in K) == 1)

    # Capacidade por viagem: carga ≤ Q_t · y[j,t]
    for j in J:
        for t in T:
            for k in K:
                solver.Add(sum(d[i] * x[i, j, t, k] for i in I) <= tipos[t]['Q'] * y[j, t])

    # L[j,t,k] ≥ dist[i] · x[i,j,t,k]
    for j in J:
        for t in T:
            for k in K:
                for i in I:
                    solver.Add(L[j, t, k] >= dist[i] * x[i, j, t, k])

    # FO: aluguel total + soma das viagens × 2 · R$/km do tipo
    solver.Minimize(
        sum(tipos[t]['rent'] * y[j, t] for j in J for t in T)
        + sum(2 * tipos[t]['ckm'] * L[j, t, k] for j in J for t in T for k in K)
    )

    status = solver.Solve()
    if status != pywraplp.Solver.OPTIMAL:
        print(f'Status não-ótimo: {status}')
        return None

    rotas = []
    for j in J:
        for t in T:
            if y[j, t].solution_value() < 0.5:
                continue
            for k in K:
                atendidos = [bares['bar'][i] for i in I if x[i, j, t, k].solution_value() > 0.5]
                if not atendidos:
                    continue
                carga = sum(d[i] for i in I if x[i, j, t, k].solution_value() > 0.5)
                rotas.append({
                    'caminhão': f'{t}{j+1}',
                    'tipo': t,
                    'viagem': k,
                    'bares': ', '.join(atendidos),
                    'caixas': carga,
                    'maior dist': L[j, t, k].solution_value(),
                })
    return {
        'custo_total': solver.Objective().Value(),
        'rotas': pd.DataFrame(rotas),
    }

sol_h = solve_fleet_heterogeneo(bares, TIPOS, MAX_PER_TYPE, VIAGENS)
print(f"Custo total: R$ {sol_h['custo_total']:,.2f}")
print()
print(sol_h['rotas'].to_string(index=False))

print(f"\nComparação:")
print(f"  Homogêneo:    R$ {sol['custo_total']:,.2f}")
print(f"  Heterogêneo:  R$ {sol_h['custo_total']:,.2f}")
print(f"  Economia:     R$ {sol['custo_total'] - sol_h['custo_total']:,.2f}")

"""### Heterogêneo em Gurobi

Mesma generalização (3 tipos × 2 viagens), agora em `gurobipy`. Note como variáveis multi-indexadas ficam mais limpas:
"""

def solve_fleet_heterogeneo_gurobi(bares, tipos, max_per_type, viagens):
    """Extensao: 3 tipos de caminhao (Pequeno/Medio/Grande) com capacidade e aluguel proprios.
    Decida quantos de cada tipo alugar + a alocacao bar -> tipo+instancia."""
    m = gp.Model('frota_het')
    m.Params.OutputFlag = 0

    # TODO: variaveis e restricoes para o problema heterogeneo
    # Dica: indexe os caminhoes como (tipo, instancia). Cada tipo t tem max_per_type[t] instancias.
    # Capacidade muda por tipo: tipos[t]['Q']

    raise NotImplementedError("Complete o modelo heterogeneo")

"""### Para discutir

1. **Qual mix de tipos o ótimo escolheu?** Compare custo fixo vs ganho de capacidade.
2. **Permitir 2 viagens muda o resultado?** Compare com a versão homogênea (1 viagem só).
3. **Sensibilidade — TODO:** rode novamente baixando o aluguel do tipo Grande para R\$ 2.400. A frota muda? A qual valor de aluguel o Grande passa a dominar?

_(Resposta da sensibilidade ficará como exercício para casa.)_
"""

# TODO: ajustar TIPOS['G']['rent'] = 2400 e rodar novamente
# tipos_v2 = dict(TIPOS)
# tipos_v2['G'] = dict(TIPOS['G'], rent=2400)
# sol_v2 = solve_fleet_heterogeneo(bares, tipos_v2, MAX_PER_TYPE, VIAGENS)
# print(sol_v2['rotas'])

"""---

## Exercício de extensão 2: CVRP completo — relaxando a aproximação de rota-estrela

Até aqui tratamos cada "rota" como **rota-estrela**: o caminhão ia direto ao bar mais distante e voltava, ignorando que precisa passar pelos outros bares do cluster. Isso subestima a distância real.

**CVRP (Capacitated Vehicle Routing Problem)** relaxa essa simplificação: o solver decide **a ordem real de visita** dentro de cada rota, otimizando a distância percorrida em todo o trajeto.

### O que muda:
- Antes: precisávamos só da **distância do CD ao bar**
- Agora: precisamos da **matriz completa** $d_{ij}$ — distância entre qualquer par de pontos (CD + 8 bares = 9 nós, matriz 9×9)

Vamos comparar 3 abordagens — uma com OR-Tools, duas com Gurobi:
1. **OR-Tools `RoutingModel`** — módulo dedicado a roteamento, com heurísticas built-in
2. **Gurobi MTZ** (Miller-Tucker-Zemlin) — formulação MILP polinomial, sem callbacks
3. **Gurobi com lazy constraints (DFJ)** — *killer feature*: subtours eliminados sob demanda durante o B&B
"""

"""### Setup: matriz de distâncias 9×9

Coordenadas aproximadas (latitude, longitude) dos pontos em São Paulo, distância calculada com aproximação esférica (1° latitude ≈ 111 km):
"""

import math

COORDS = {
    'CD':            (-23.567, -46.685),
    'Centro':        (-23.553, -46.635),
    'Pinheiros':     (-23.565, -46.685),
    'Vila Madalena': (-23.555, -46.692),
    'Moema':         (-23.605, -46.665),
    'Tatuapé':       (-23.539, -46.572),
    'Lapa':          (-23.521, -46.706),
    'Itaim':         (-23.583, -46.671),
    'Brooklin':      (-23.612, -46.690),
}
NODES = list(COORDS.keys())
N = len(NODES)
DEPOT = 0
CUSTOMERS = list(range(1, N))

def km(a, b):
    return math.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2) * 111

# Matriz de distâncias km
D = {(i, j): km(COORDS[NODES[i]], COORDS[NODES[j]]) for i in range(N) for j in range(N)}

# Demanda (re-aproveita do caso simples)
DEM = [0] + bares['d'].tolist()  # 0 para o depot

# Mostra a matriz
import pandas as pd
M = pd.DataFrame(
    [[D[i,j] for j in range(N)] for i in range(N)],
    index=NODES, columns=NODES
).round(1)
print('Matriz de distâncias (km):')
M

"""### 1) OR-Tools `RoutingModel` — solver dedicado a VRP

OR-Tools tem um **módulo de routing** separado, com heurísticas (PATH_CHEAPEST_ARC, SAVINGS) + busca local (Guided Local Search). Sintaxe diferente do `linear_solver` (pywraplp):
"""

from ortools.constraint_solver import pywrapcp, routing_enums_pb2
import time

def solve_cvrp_ortools(D, DEM, Q, max_veh, fixed_cost_decimo=5000, time_limit=10):
    # OR-Tools quer distâncias em inteiros — usamos décimos de km
    Dint = [[int(round(D[i,j] * 10)) for j in range(N)] for i in range(N)]

    mgr = pywrapcp.RoutingIndexManager(N, max_veh, DEPOT)
    rt = pywrapcp.RoutingModel(mgr)

    # Callback de distância
    def dist_cb(from_idx, to_idx):
        return Dint[mgr.IndexToNode(from_idx)][mgr.IndexToNode(to_idx)]
    transit = rt.RegisterTransitCallback(dist_cb)
    rt.SetArcCostEvaluatorOfAllVehicles(transit)

    # Callback de demanda (com dimensão de capacidade)
    def demand_cb(from_idx):
        return DEM[mgr.IndexToNode(from_idx)]
    demand_idx = rt.RegisterUnaryTransitCallback(demand_cb)
    rt.AddDimensionWithVehicleCapacity(demand_idx, 0, [Q]*max_veh, True, 'Capacity')

    # Custo fixo por veículo usado (R$ 2.000 = 5.000 décimos de unidade da FO)
    for v in range(max_veh):
        rt.SetFixedCostOfVehicle(fixed_cost_decimo, v)

    # Search params
    params = pywrapcp.DefaultRoutingSearchParameters()
    params.first_solution_strategy = routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    params.local_search_metaheuristic = routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH
    params.time_limit.seconds = time_limit

    t0 = time.time()
    sol = rt.SolveWithParameters(params)
    t = time.time() - t0
    if sol is None:
        return None

    rotas = []
    total_km = 0
    for v in range(max_veh):
        idx = rt.Start(v)
        if rt.IsEnd(sol.Value(rt.NextVar(idx))):
            continue
        seq = []
        while not rt.IsEnd(idx):
            seq.append(NODES[mgr.IndexToNode(idx)])
            idx = sol.Value(rt.NextVar(idx))
        seq.append(NODES[mgr.IndexToNode(idx)])
        d_rota = sum(D[NODES.index(seq[i]), NODES.index(seq[i+1])] for i in range(len(seq)-1))
        rotas.append({'rota': ' → '.join(seq),
                      'caixas': sum(DEM[NODES.index(n)] for n in seq),
                      'km': d_rota})
        total_km += d_rota
    return {'rotas': rotas, 'total_km': total_km,
            'n_veic': len(rotas),
            'custo': 2000*len(rotas) + 4*total_km,
            'tempo_ms': t*1000}

sol_ortools = solve_cvrp_ortools(D, DEM, Q, MAX_TRUCKS)
print(f"OR-Tools RoutingModel:  custo = R$ {sol_ortools['custo']:,.2f}  ({sol_ortools['n_veic']} veículos, {sol_ortools['total_km']:.1f} km, {sol_ortools['tempo_ms']:.0f} ms)")
for r in sol_ortools['rotas']:
    print(f"  {r['rota']:<60} {r['caixas']:>3} cx, {r['km']:.1f} km")

"""### 2) Gurobi MTZ — formulação MILP polinomial

Variáveis:
- $x_{ijk} \in \{0,1\}$: veículo $k$ usa o arco $i \to j$
- $y_k \in \{0,1\}$: veículo $k$ é usado
- $u_{ik} \ge 1$: ordem de visita do cliente $i$ pelo veículo $k$ (MTZ)

Restrição-chave de **eliminação de subtour (MTZ)**: para cada par $(i, j)$ de clientes e cada veículo $k$:
$$u_{ik} - u_{jk} + (n-1)\,x_{ijk} \le n - 2$$

Lê-se: se $x_{ijk} = 1$ (veículo $k$ vai de $i$ para $j$), então $u_{jk} \ge u_{ik} + 1$ — a ordem cresce.
"""

import gurobipy as gp
from gurobipy import GRB
from itertools import product

def solve_cvrp_gurobi_mtz(D, DEM, Q, max_veh):
    """CVRP com formulacao MTZ (Miller-Tucker-Zemlin): variaveis u[i,k] de ordem.
    Veja a discussao no deck sobre por que MTZ tem $O(n^2)$ restricoes."""
    N = range(len(DEM))
    V = range(max_veh)
    m = gp.Model('cvrp_mtz')
    m.Params.OutputFlag = 0

    # TODO: variaveis
    # x[i,j,v] binaria: arco (i,j) percorrido pelo veiculo v
    # u[i,k] continua: ordem do bar i na rota do veiculo k (para eliminar subtour)

    # TODO: restricoes
    # - cada bar atendido por exatamente 1 veiculo
    # - fluxo: entradas == saidas em cada no
    # - capacidade por veiculo
    # - MTZ: u[i,k] - u[j,k] + (n-1)*x[i,j,k] <= n-2  forall i,j em [1..n-1], i!=j

    # TODO: FO = minimizar distancia total + custo fixo dos veiculos usados

    raise NotImplementedError("Complete o modelo MTZ acima")

"""### 3) Gurobi com lazy constraints (DFJ + callbacks) — o killer feature

**Dantzig-Fulkerson-Johnson (DFJ)** elimina subtour de outra forma: para qualquer subconjunto $S$ de clientes,
$$\sum_{i,j \in S,\ i \ne j} x_{ijk} \le |S| - 1$$

Problema: o **número de subconjuntos é exponencial** ($2^n$). Não dá pra adicionar todas as restrições upfront.

**Solução elegante (só em solvers comerciais):** *callbacks*. O solver Gurobi nos dá um *hook* dentro do B&B — toda vez que ele encontra uma solução inteira, chamamos uma função Python que:
1. Procura subtour na solução corrente
2. Se encontrar, adiciona a constraint específica como **lazy constraint**
3. Continua o B&B

É uma das razões clássicas para investir em Gurobi/CPLEX em problemas de roteamento de larga escala — solvers open-source com suporte a callbacks são raros.
"""

def solve_cvrp_gurobi_callbacks(D, DEM, Q, max_veh):
    """CVRP com DFJ + lazy callbacks: SEM as variaveis u do MTZ.
    Subtours sao detectados via callback durante o B&B e adicionados como restricoes lazy."""

    # TODO: monte o modelo base (vars x, y, sem u, sem MTZ)

    # TODO: defina o callback subtour_callback(model, where)
    #   - filtre por where == GRB.Callback.MIPSOL
    #   - leia solucao via cbGetSolution
    #   - detecte ciclos desconectados do deposito
    #   - adicione DFJ via cbLazy: sum_{i,j in S} x[i,j] <= |S| - 1

    # TODO: m._x = x ; m.Params.LazyConstraints = 1 ; m.optimize(subtour_callback)

    raise NotImplementedError("Complete o modelo DFJ+lazy acima")

"""### Comparação das três abordagens

Vamos sumarizar:
"""

comparacao = pd.DataFrame([
    {'método': 'Rota-estrela (caso simples)',     'custo': sol['custo_total'],         'tempo (ms)': '—'},
    {'método': 'OR-Tools RoutingModel',           'custo': sol_ortools['custo'],       'tempo (ms)': f"{sol_ortools['tempo_ms']:.0f}"},
    {'método': 'Gurobi MTZ (MILP exato)',         'custo': sol_mtz['custo'],           'tempo (ms)': f"{sol_mtz['tempo_ms']:.0f}"},
    {'método': 'Gurobi DFJ + lazy constraints',   'custo': sol_dfj['custo'],           'tempo (ms)': f"{sol_dfj['tempo_ms']:.0f}"},
])
comparacao['custo'] = comparacao['custo'].apply(lambda v: f'R$ {v:,.2f}')
print(comparacao.to_string(index=False))

"""### Lições deste módulo

1. **A rota-estrela subestima o custo real.** Para o caso Beerlink, o custo real do plano (R$ 8.250) é R$ 49 maior do que a estimativa otimista (R$ 8.201). Em problemas maiores essa subestimação pode ser de 10–30 %.

2. **Para problemas pequenos, qualquer solver serve.** OR-Tools, Gurobi MTZ e Gurobi DFJ convergem para a mesma resposta. Escolha pela ergonomia do código.

3. **Em problemas reais (50+ clientes), CVRP fica difícil.** É aí que a estratégia muda:
   - **OR-Tools RoutingModel** continua ótimo para problemas até centenas de clientes — heurísticas + busca local
   - **Gurobi + lazy constraints** é o padrão da indústria para CVRP exato com 50–100 clientes — separação de subtour just-in-time é fundamental
   - **Heurísticas dedicadas** (LKH, HGS, etc.) vão além para milhares de nós

4. **Lazy constraints é um recurso pago.** Solvers open-source (CBC, GLPK) não oferecem, ou oferecem de forma muito limitada. Este é um dos casos onde a licença Gurobi se paga em projetos de roteamento.
"""
